VerificacionBundle_automotor:
    resource: "@VerificacionBundle/Resources/config/routing/automotor.yml"
    prefix:   /automotor

VerificacionBundle_automotor_importar:
    resource: "@VerificacionBundle/Resources/config/routing/importar.yml"
    prefix:   /automotor

VerificacionBundle_automotor_exportar:
    resource: "@VerificacionBundle/Resources/config/routing/exportar.yml"
    prefix:   /automotor/exportar