automotor:
    pattern:  /
    defaults: { _controller: "VerificacionBundle:Automotor:index" }

automotor_show:
    pattern:  /{id}/show
    defaults: { _controller: "VerificacionBundle:Automotor:show" }

automotor_mysql:
    pattern:  /mysql
    defaults: { _controller: "VerificacionBundle:Automotor:mysql" }
