usuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

infraccion:
    resource: "@InfraccionBundle/Resources/config/routing.yml"
    prefix:   /

verificacion:
    resource: "@VerificacionBundle/Resources/config/routing.yml"
    prefix:   /verificacion

foto_manager:
    resource: "@FotoManagerBundle/Resources/config/routing.yml"
    prefix:   /


lar_utils:
    resource: "@LarUtilsBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

home_page:
    pattern:   /
    defaults: { _controller: "InfraccionBundle:Infraccion:filterParm" }

