infraccion:
    pattern:  /
    defaults: { _controller: "InfraccionBundle:Infraccion:index" }

infraccion_show:
    pattern:  /{id}/show
    defaults: { _controller: "InfraccionBundle:Infraccion:show" }

infraccion_new:
    pattern:  /new
    defaults: { _controller: "InfraccionBundle:Infraccion:new" }

infraccion_create:
    pattern:  /create
    defaults: { _controller: "InfraccionBundle:Infraccion:create" }
    requirements: { _method: post }

infraccion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "InfraccionBundle:Infraccion:edit" }

infraccion_update:
    pattern:  /{id}/update
    defaults: { _controller: "InfraccionBundle:Infraccion:update" }
    requirements: { _method: post|put }

infraccion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "InfraccionBundle:Infraccion:delete" }
    requirements: { _method: post|delete }


infraccion_filterparm:
    pattern:  /filterparm
    defaults: { _controller: "InfraccionBundle:Infraccion:filterParm" }

infraccion_filterparm_refubi:
    pattern:  /filterparm_refubi
    defaults: { _controller: "InfraccionBundle:Infraccion:refreshUbicaciones" }

infraccion_dominio_edit:
    pattern: /edit_dominio_ajax
    defaults: { _controller: "InfraccionBundle:Automotor:domionioAjaxEdit" }

infraccion_dominio_save:
    pattern: /{id}/save_dominio_ajax
    defaults: { _controller: "InfraccionBundle:Automotor:dominioAjaxSave" }
    requirements: { _method: post }

infraccion_cambiar_foto:
    pattern: /{id}/infraccion_cambiarfoto
    defaults: { _controller: "InfraccionBundle:Infraccion:cambiarFoto" }
    requirements: { _method: post }