<?php

namespace Infraccion\infraccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class InfraccionRepository extends EntityRepository
{
   public function getInfraccionByDatos($muni,$ubi,$tipoInf,$dom, $fecha){
        $reg = $this->findBy(array('municipio'=> $muni, 'ubicacion' => $ubi, "tipo_infraccion" => $tipoInf, "dominio" => $dom, "fecha" => $fecha ) );
        if(count($reg) >0 ){
            return $reg[0];
        }

       return null;
   }

    /**
     * @param $muni
     * @param $ubi
     * @param $tipo
     * @param Datetime $fecha
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getInfraccionQuery($muni, $ubi, $tipo,$fecha)
    {
        $fecha2 = clone($fecha);
        $a = $this->createQueryBuilder("r")
//            ->leftJoin("VerificacionBundle:Automotor","a",\Doctrine\ORM\Query\Expr\Join::LEFT_JOIN,"r.dominio = a.dominio")
            ->where("r.municipio = :muni")
            ->andWhere("r.ubicacion = :ubic")
            ->andWhere("r.tipo_infraccion = :tipo")
            ->andWhere("r.fecha between :fechaDesde and :fechaHasta")
            ->orderBy('r.fecha')
            ->setParameter("muni", $muni)
            ->setParameter("ubic", $ubi)
            ->setParameter("tipo", $tipo)
            ->setParameter("fechaDesde", $fecha)
            ->setParameter("fechaHasta", $fecha2->setTime(23,59) )
            ;
        return $a;
    }

}
