<?php

namespace Infraccion\infraccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfraccionRepository extends EntityRepository
{
   public function getInfraccionByDatos($muni,$ubi,$tipoInf,$dom, $fecha){
        $reg = $this->findBy(array('municipio'=> $muni, 'ubicacion' => $ubi, "tipo_infraccion" => $tipoInf, "dominio" => $dom, "fecha" => $fecha ) );
        if(count($reg) >0 ){
            return $reg[0];
        }

       return null;
   }

}
