<?php

namespace Infraccion\infraccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoInfraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInfraccionRepository extends EntityRepository
{
}
