<?php

namespace Infraccion\infraccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UbicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbicacionRepository extends EntityRepository
{
    public function getUbicacionByMuni($muni) {
        return  $this->createQueryBuilder("s")
            ->where("s.municipio= :muni")
            ->setParameter("muni", $muni)
            ->addOrderBy("s.ubicacion", "asc");

     /*   $aTabla = array();

        $parametros = $q->getResult();


//        foreach ($parametros as $parametro) {
//            $aTabla[$parametro->getId()] = $parametro->__toString();
//        }

        return $parametros //$aTabla;
*/
    }
}
