parameters:
#    infraccion.example.class: Infraccion\infraccionBundle\Example

services:
#    infraccion.example:
#        class: %infraccion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
